version: '3.8'

services:
  esfs-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esfs-vitrine
    ports:
      - "8080:80" # Map le port 8080 de votre machine vers le port 80 du conteneur (Nginx)
    restart: unless-stopped
    environment:
      - NODE_ENV=production
